export const blogs = [
  {
    id: 1,
    title: "Olahraga sederhana untuk meningkatkan stamina",
    category: "Lari",
    image: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5",
    type: "video",
    description: "Latihan dasar untuk meningkatkan daya tahan tubuh",
  },
  {
    id: 2,
    title: "Latihan untuk kekuatan dan kebugaran tubuh",
    category: "Fitness",
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a",
    type: "video",
    description: "Program latihan untuk membentuk otot dan kebugaran",
  },
  {
    id: 3,
    title: "Teknik dasar: Breathing, Pacing, dan Teknik Kayuh",
    category: "Bersepeda",
    image: "https://images.unsplash.com/photo-1517649763962-0c623066013b",
    type: "video",
    description: "Panduan dasar bersepeda untuk pemula",
  },
  {
    id: 4,
    title: "Cara menggiring bola seperti profesional",
    category: "Sepak Bola",
    image: "https://images.unsplash.com/photo-1518091043644-c1d4457512c6",
    type: "video",
    description: "Teknik dribbling yang sering digunakan pemain top",
  },
  {
    id: 5,
    title: "Teknik shooting akurat dalam basket",
    category: "Basket",
    image: "https://images.unsplash.com/photo-1546519638-68e109498ffc",
    type: "video",
    description: "Latihan untuk meningkatkan akurasi tembakan",
  },
  {
    id: 6,
    title: "Teknik pernapasan dalam renang",
    category: "Renang",
    image: "https://images.unsplash.com/photo-1508609349937-5ec4ae374ebf",
    type: "video",
    description: "Belajar mengatur napas saat berenang",
  },
];